# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import patchwork_pb2 as patchwork__pb2


class PatchworkServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetStaticConfig = channel.unary_unary(
        '/PatchworkServer/GetStaticConfig',
        request_serializer=patchwork__pb2.StaticConfigRequest.SerializeToString,
        response_deserializer=patchwork__pb2.StaticConfigReply.FromString,
        )
    self.Create = channel.unary_unary(
        '/PatchworkServer/Create',
        request_serializer=patchwork__pb2.CreateRequest.SerializeToString,
        response_deserializer=patchwork__pb2.CreateReply.FromString,
        )
    self.PerformMove = channel.unary_unary(
        '/PatchworkServer/PerformMove',
        request_serializer=patchwork__pb2.MoveRequest.SerializeToString,
        response_deserializer=patchwork__pb2.MoveReply.FromString,
        )


class PatchworkServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetStaticConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PerformMove(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PatchworkServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetStaticConfig': grpc.unary_unary_rpc_method_handler(
          servicer.GetStaticConfig,
          request_deserializer=patchwork__pb2.StaticConfigRequest.FromString,
          response_serializer=patchwork__pb2.StaticConfigReply.SerializeToString,
      ),
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=patchwork__pb2.CreateRequest.FromString,
          response_serializer=patchwork__pb2.CreateReply.SerializeToString,
      ),
      'PerformMove': grpc.unary_unary_rpc_method_handler(
          servicer.PerformMove,
          request_deserializer=patchwork__pb2.MoveRequest.FromString,
          response_serializer=patchwork__pb2.MoveReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PatchworkServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
