# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import patchwork_pb2 as patchwork__pb2


class PatchworkServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetStaticConfig = channel.unary_unary(
        '/PatchworkServer/GetStaticConfig',
        request_serializer=patchwork__pb2.StaticConfigRequest.SerializeToString,
        response_deserializer=patchwork__pb2.StaticConfigReply.FromString,
        )
    self.Evaluate = channel.unary_unary(
        '/PatchworkServer/Evaluate',
        request_serializer=patchwork__pb2.EvaluateRequest.SerializeToString,
        response_deserializer=patchwork__pb2.EvaluateReply.FromString,
        )
    self.Train = channel.unary_unary(
        '/PatchworkServer/Train',
        request_serializer=patchwork__pb2.TrainRequest.SerializeToString,
        response_deserializer=patchwork__pb2.TrainReply.FromString,
        )


class PatchworkServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetStaticConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Evaluate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Train(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PatchworkServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetStaticConfig': grpc.unary_unary_rpc_method_handler(
          servicer.GetStaticConfig,
          request_deserializer=patchwork__pb2.StaticConfigRequest.FromString,
          response_serializer=patchwork__pb2.StaticConfigReply.SerializeToString,
      ),
      'Evaluate': grpc.unary_unary_rpc_method_handler(
          servicer.Evaluate,
          request_deserializer=patchwork__pb2.EvaluateRequest.FromString,
          response_serializer=patchwork__pb2.EvaluateReply.SerializeToString,
      ),
      'Train': grpc.unary_unary_rpc_method_handler(
          servicer.Train,
          request_deserializer=patchwork__pb2.TrainRequest.FromString,
          response_serializer=patchwork__pb2.TrainReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PatchworkServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
